name: Xamarin-UI-PullRequest

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/xamarin-ui-build.yml
    with: 
      app-version: 1.0.${{ github.event.pull_request.number }}.${{ github.run_number }}
      configuration: Release
    secrets: inherit  

  notify:
    if: ${{ success() }}
    needs: build
    uses: ./.github/workflows/xamarin-ui-notify.yml
    secrets: inherit